### ISSUE TITLE
Error package titlesec

### ISSUE THREAD

**Issue by MatthiasFl** [tudelftgeomatics/thesis_template#6]
Very nice template! However, i continously get some warnings concerning 'Package titlesec', like 'Package titlesec Warning: Non standard sectioning command \subsection detected. Using default spacing and no format.' Is there any possibility to cover this warning or include a workaround?

**Comment by hugoledoux** [comment]
The packages I used indeed created a lot of warnings, new versions of latex and other packages created this. I couldn't really solve them, so I went to a simpler template, just pushed to master now.

It's less pretty, but simpler to maintain and I get less questions from students...

**Comment by fdahle** [comment]
I found a workaround to fix the warnings that do not have an effect but are annoying in the log-files.
In thesis.tex these commands must be entered. Note that it must be called before creating the document, so instead of \usepackage \RequirePackage is needed. 

`%Remove some warnings that are created by arsclassica and have no effect
\RequirePackage{silence}
\WarningFilter{titlesec}{Non standard sectioning command}
\WarningFilter{hyperref}{Option}
\WarningFilter{tocloft}{\@starttoc has already been redefined}
`


More warnings can be filtered. The first brackets define the package, the second brackets define the text of the warning (not the complete text must be inserted, only the beginning)

**Comment by hugoledoux** [comment]
thanks @fdahle , but I have decided to simplify the template and use less fancy fonts/commands. It's also more future-proof...

It still looks good, a bit less, but fine enough IMO.

Feel free to use what you want though.
